backweb/urls.py
from django.conf.urls import url

from backweb import views

urlpatterns = [
    # 文章
    # 添加文章内容
    url(r'^add_art/', views.add_art, name='add'),
    # 文章首页
    url(r'^art/', views.art, name='art_list'),
    # 编辑文章
    url(r'^edit_art/(\d+)/', views.edit_art, name='edit_art'),
    # 删除文章
    url(r'^del_art/(\d+)/', views.del_art, name='del_art'),

    # 注册
    url(r'^register/', views.register),
    # 登陆
    url(r'^login/', views.login),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from blog.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^backweb/', include('backweb.urls', namespace='art')),
    url(r'^web/', include('web.urls', namespace='web_art'))
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

web/urls.py
from django.conf.urls import url

from web import views

urlpatterns = [
    url(r'^share/', views.share, name='share'),
    url(r'^my_index/', views.my_index),
]

backweb/models.py
from django.db import models

from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=150)
    content = models.TextField()
    icon = models.ImageField(upload_to='article')
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'article'


class MyUser(models.Model):
    username = models.CharField(max_length=10, unique=True)
    password = models.CharField(max_length=10)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'user'

web/models.py
from django.db import models

# Create your models here.

backweb/views.py
from django.shortcuts import render

from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from backweb.Artform import AddArtForm, Register, EditArt
from backweb.models import Article, MyUser
from django.core.paginator import Paginator


def add_art(request):
    if request.method == 'GET':
        return render(request, 'backweb/add_article.html')
    if request.method == 'POST':
        form = AddArtForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data['desc']
            content = form.cleaned_data['content']
            icon = form.cleaned_data['icon']
            Article.objects.create(title=title, desc=desc, content=content, icon=icon)
        # 创建成功后，返回文章列表
            return HttpResponseRedirect(reverse('art:art_list'))
        else:
            return render(request, 'backweb/add_article.html', {'form': form})


def art(request):
    if request.method == 'GET':
        page = int(request.GET.get('page', 1))
        articles = Article.objects.all()
        paginator = Paginator(articles, 3)
        pages = paginator.page(page)
        return render(request, 'backweb/art.html', {'pages': pages})


def edit_art(request, id):
    if request.method == 'GET':
        article = Article.objects.filter(pk=id).first()
        return render(request, 'backweb/add_article.html', {'article': article})
    if request.method == 'POST':
        form = EditArt(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            desc = form.cleaned_data['desc']
            content = form.cleaned_data['content']
            icon = form.cleaned_data['icon']
            article = Article.objects.filter(pk=id).first()
            article.title = title
            article.desc = desc
            article.content = content
            if icon:
                article.icon = icon
            article.save()
            return HttpResponseRedirect(reverse('art:art_list'))
        else:
            article = Article.objects.filter(pk=id).first()
            return render(request, 'backweb/add_article.html', {'form': form, 'article': article})


def del_art(request, id):
    if request.method == 'GET':
        Article.objects.filter(pk=id).delete()
        return HttpResponseRedirect(reverse('art:art_list'))


def register(request):
    if request.method == 'GET':
        return render(request, 'backweb/register.html')

    if request.method == 'POST':
        form = Register(request.POST, request.FILES)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            password2 = form.cleaned_data['password2']
            u_name = MyUser.objects.filter(username=username).first()
            if u_name:
                err_name = '该账号已经注册过了'
                return render(request, 'backweb/register.html', {'err_name': err_name})
            if password != password2:
                err_name = '两次密码不一致！'
                return render(request, 'backweb/register.html', {'err_name': err_name})
            MyUser.objects.create(username=username, password=password)
            return HttpResponseRedirect('/backweb/login/')
        else:
            return render(request, 'backweb/register.html', {'form': form})

        # username = request.POST.get('username')
        # password = request.POST.get('password')
        # password2 = request.POST.get('password2')
        # u_name = MyUser.objects.filter(username=username).first()
        # if u_name:
        #     err_name = '该账号已经注册过了'
        #     return render(request, 'register.html', {'err_name': err_name})
        # if password and password2:
        #     if password != password2:
        #         err_name = '两次密码不一致'
        #         return render(request, 'register.html', {'err_name': err_name})
        # else:
        #     err_name = '密码不能为空'
        #     return render(request, 'register.html', {'err_name': err_name})
        # MyUser.objects.create(username=username, password=password)
        # return HttpResponseRedirect('/login/')


def login(request):
    if request.method == 'GET':
        return render(request, 'backweb/login.html')

    if request.method == 'POST':
        u = request.POST.get('username')
        p = request.POST.get('password')
        user = MyUser.objects.filter(username=u, password=p).first()
        if not user:
            err_name = '账号或者密码错误'
            return render(request, 'backweb/login.html', {'err_name': err_name})
        request.session['user_id'] = user.id
        return HttpResponseRedirect('/backweb/art/')

web/views.py
from django.shortcuts import render, HttpResponseRedirect

from backweb.models import Article





def share(request):
    if request.method == 'GET':
        return render(request, 'web/share.html')


def my_index(request):
    if request.method == 'GET':
        arts = Article.objects.all()
        return render(request, 'web/index.html', {'arts': arts})

templates/backweb/add_article.html
{% extends 'backweb/base.html' %}
{% block title %}
    article
{% endblock %}
{% block h1 %}
  操作
{% endblock %}
{% block right %}

<div class="row">
        <form action="" method="post" class="add-article-form" enctype="multipart/form-data">
            {{ form.error }}
            {% csrf_token %}
          <div class="col-md-9">
            <h1 class="page-header">撰写新文章</h1>
            <div class="form-group">
              <label for="article-title" class="sr-only">标题</label>
              <input type="text" id="article-title" name="title" class="form-control" placeholder="在此处输入标题" value="{{ article.title}}">
                <p style="color:red">{{ form.errors.title }}</p>
            </div>
            <div class="form-group">
              <textarea class="sr-only" id="editor_id" name="content">{{ article.content }}</textarea>
                <p style="color:red">{{ form.errors.content }}</p>
            </div>

            <div class="add-article-box">
              <h2 class="add-article-box-title" ><span>描述</span></h2>
              <div class="add-article-box-content">
              	<textarea class="form-control" name="desc" autocomplete="off">{{ article.desc }}</textarea>
                  <p style="color: red">{{ form.errors.desc }}</p>
                <span class="prompt-text">描述内容总结，并可以在网页描述中使用</span>
              </div>
            </div>

                 <P>首图: <input type='file' name="icon">
                                 {% if article.icon %}
                                    <img src="/media/{{ article.icon }}">
                                {%  endif %}
              <input type="submit" value="提交">
          </div>


{% endblock %}
{% block js %}
    {% load static %}
    <script src="{% static 'kindeditor/kindeditor-all-min.js' %}" type="text/javascript"></script>
    <script src="{% static 'kindeditor/lang/zh-CN.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
            window.editor = K.create('#editor_id',{
                uploadJson:'/util/upload/kindeditor'
            });
        });
    </script>
{% endblock %}

templates/backweb/art.html
{% extends 'backweb/base.html' %}
{% block title %}
    article
{% endblock %}
{% block h1 %}
  操作
{% endblock %}
{% block right %}

<form action="" method="post" alt="" enctype="multipart/form-data">
                {% csrf_token %}

        <h1 class="page-header">操作</h1>
        <ol class="breadcrumb">
          <li><a href="/backweb/add_art/">增加文章</a></li>
        </ol>
        <h1 class="page-header">管理 <span class="badge">{{ pages.paginator.count }}</span></h1>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">选择</span></th>
                <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">标题</span></th>
                 <th><span class=""></span> <span class=""></span>内容</th>
                <th><span class=""></span> <span class=""></span>描述</th>
                <th><span class=""></span> <span class=""></span>日期</th>
                <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">图片</span></th>
                <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
              </tr>
            </thead>
            {% for page in pages %}
            <tbody>
              <tr>
                <td><input type="checkbox" class="input-control" name="checkbox[]" value="" /></td>
                <td class="article-title">{{ page.title }} </td>
                <td class="article-title">{{ page.content }} </td>
                <td class="hidden-sm">{{ page.desc }}</td>
                <td class="hidden-sm">{{ page.create_time }}</td>

                <td><img width="50" height="50" alt=""  src="/media/{{ page.icon }}"></td>
                <td>
                    <a href="{% url 'art:edit_art' page.id %}">编辑</a>
                    <a href="{% url 'art:del_art' page.id %}">删除</a>

                </td>
              </tr>
            </tbody>
            {% endfor %}
          </table>
        </div>
        <footer class="message_footer">
          <nav>
            <div class="btn-toolbar operation" role="toolbar">
              <div class="btn-group" role="group"> <a class="btn btn-default" onClick="select()">全选</a> <a class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default" onClick="noselect()">不选</a> </div>
              <div class="btn-group" role="group">
                <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="删除全部选中" name="checkbox_delete">删除</button>
              </div>
            </div>
            <ul class="pagination pagenav">
                    {% if pages.has_previous %}
              <li><a href="{% url 'art:art_list' %}?page={{ pages.previous_page_number }}" aria-label="Previous" > <span aria-hidden="true">&laquo;</span> </a> </li>
                    {% endif %}
            {% for page in pages.paginator.page_range %}
              <li><a href="{% url 'art:art_list' %}?page={{ page }}">{{ page }}</a></li>
            {% endfor %}
                    {% if pages.has_next %}
              <li><a href="{% url 'art:art_list' %}?page={{ pages.next_page_number }}" aria-label="Next"> <span aria-hidden="true">&raquo;</span> </a> </li>
                    {% endif %}
            </ul>
          </nav>
        </footer>
      </form>

{% endblock %}

templates/backweb/base.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>
    {% block title %}
    {% endblock %}
</title>
    {% block css %}
<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
<link rel="apple-touch-icon-precomposed" href="/static/images/icon/icon.png">
<link rel="shortcut icon" href="/static/images/icon/favicon.ico">
<script src="/static/js/jquery-2.1.4.min.js"></script>
<!--[if gte IE 9]>
  <script src="/static/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="/static/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="/static/js/respond.min.js" type="text/javascript"></script>
  <script src="/static/js/selectivizr-min.js" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
  <script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
    {% endblock %}
</head>

<body class="user-select">
<section class="container-fluid">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">YlsatCMS</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">消息 <span class="badge">1</span></a></li>
            <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }} <span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
              </ul>
            </li>
            <li><a href="login.html" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a data-toggle="modal" data-target="#WeChat">帮助</a></li>
          </ul>
          <form action="" method="post" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="">报告</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'art:art_list' %}">文章</a></li>
        <li><a href="notice.html" title="下面的功能还在开发当中哦">公告</a></li>
        <li><a href="comment.html">评论</a></li>
        <li><a data-toggle="tooltip" data-placement="bottom" title="网站暂无留言功能">留言</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a class="dropdown-toggle" id="otherMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">其他</a>
          <ul class="dropdown-menu" aria-labelledby="otherMenu">
            <li><a href="flink.html">友情链接</a></li>
            <li><a data-toggle="modal" data-target="#areDeveloping">访问记录</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a class="dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">用户</a>
          <ul class="dropdown-menu" aria-labelledby="userMenu">
            <li><a data-toggle="modal" data-target="#areDeveloping">管理用户组</a></li>
            <li><a href="manage-user.html">管理用户</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="loginlog.html">管理登录日志</a></li>
          </ul>
        </li>
        <li><a class="dropdown-toggle" id="settingMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">设置</a>
          <ul class="dropdown-menu" aria-labelledby="settingMenu">
            <li><a href="setting.html">基本设置</a></li>
            <li><a href="readset.html">阅读设置</a></li>
            <li role="separator" class="divider"></li>
            <li><a data-toggle="modal" data-target="#areDeveloping">安全配置</a></li>
            <li role="separator" class="divider"></li>
            <li class="disabled"><a>扩展菜单</a></li>
          </ul>
        </li>
      </ul>
    </aside>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <h1 class="page-header">
          {% block h1 %}
          {% endblock %}
      </h1>
      {% block right %}
        {% endblock %}
  </div>
  </div>
</section>
<!--个人信息模态框-->
<div class="modal fade" id="seeUserInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <form action="" method="post">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" >个人信息</h4>
        </div>
        <div class="modal-body">
          <table class="table" style="margin-bottom:0px;">
            <thead>
              <tr> </tr>
            </thead>
            <tbody>
              <tr>
                <td wdith="20%">姓名:</td>
                <td width="80%"><input type="text" value="王雨" class="form-control" name="truename" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">用户名:</td>
                <td width="80%"><input type="text" value="admin" class="form-control" name="username" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">电话:</td>
                <td width="80%"><input type="text" value="18538078281" class="form-control" name="usertel" maxlength="13" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">旧密码:</td>
                <td width="80%"><input type="password" class="form-control" name="old_password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">新密码:</td>
                <td width="80%"><input type="password" class="form-control" name="password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">确认密码:</td>
                <td width="80%"><input type="password" class="form-control" name="new_password" maxlength="18" autocomplete="off" /></td>
              </tr>
            </tbody>
            <tfoot>
              <tr></tr>
            </tfoot>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
          <button type="submit" class="btn btn-primary">提交</button>
        </div>
      </div>
    </form>
  </div>
</div>
<!--个人登录记录模态框-->
<div class="modal fade" id="seeUserLoginlog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" >登录记录</h4>
      </div>
      <div class="modal-body">
          <table class="table" style="margin-bottom:0px;">
            <thead>
              <tr>
                <th>登录IP</th>
                <th>登录时间</th>
                <th>状态</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>::1:55570</td>
                <td>2016-01-08 15:50:28</td>
                <td>成功</td>
              </tr>
              <tr>
                <td>::1:64377</td>
                <td>2016-01-08 10:27:44</td>
                <td>成功</td>
              </tr>
              <tr>
                <td>::1:64027</td>
                <td>2016-01-08 10:19:25</td>
                <td>成功</td>
              </tr>
              <tr>
                <td>::1:57081</td>
                <td>2016-01-06 10:35:12</td>
                <td>成功</td>
              </tr>
            </tbody>
          </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--微信二维码模态框-->
<div class="modal fade user-select" id="WeChat" tabindex="-1" role="dialog" aria-labelledby="WeChatModalLabel">
  <div class="modal-dialog" role="document" style="margin-top:120px;max-width:280px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="WeChatModalLabel" style="cursor:default;">微信扫一扫</h4>
      </div>
      <div class="modal-body" style="text-align:center"> <img src="images/weixin.jpg" alt="" style="cursor:pointer"/> </div>
    </div>
  </div>
</div>
<!--提示模态框-->
<div class="modal fade user-select" id="areDeveloping" tabindex="-1" role="dialog" aria-labelledby="areDevelopingModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="areDevelopingModalLabel" style="cursor:default;">该功能正在日以继夜的开发中…</h4>
      </div>
      <div class="modal-body"> <img src="images/baoman/baoman_01.gif" alt="深思熟虑" />
        <p style="padding:15px 15px 15px 100px; position:absolute; top:15px; cursor:default;">很抱歉，程序猿正在日以继夜的开发此功能，本程序将会在以后的版本中持续完善！</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--右键菜单列表-->
<div id="rightClickMenu">
  <ul class="list-group rightClickMenuList">
    <li class="list-group-item disabled">欢迎访问异清轩博客</li>
    <li class="list-group-item"><span>IP：</span>172.16.10.129</li>
    <li class="list-group-item"><span>地址：</span>河南省郑州市</li>
    <li class="list-group-item"><span>系统：</span>Windows10 </li>
    <li class="list-group-item"><span>浏览器：</span>Chrome47</li>
  </ul>
</div>
    {% block js %}
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/admin-scripts.js"></script>
    {% endblock %}
</body>
</html>

templates/backweb/login.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>异清轩博客管理系统</title>
<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/css/login.css">
<link rel="apple-touch-icon-precomposed" href="/static/images/icon/icon.png">
<link rel="shortcut icon" href="/static/images/icon/favicon.ico">
<script src="/static/js/jquery-2.1.4.min.js"></script>
<!--[if gte IE 9]>
  <script src="/static/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="/static/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="/static/js/respond.min.js" type="text/javascript"></script>
  <script src="/static/js/selectivizr-min.js" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
  <script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
</head>

<body class="user-select">
{{ err_data }}
<div class="container">
  <div class="siteIcon"><img src="/static/images/icon/1.jpg" alt="" data-toggle="tooltip" data-placement="top" title="欢迎使用异清轩博客管理系统" draggable="false" /></div>
  <form action="" method="post" autocomplete="off" class="form-signin">
    {{ err_name }}
    {% csrf_token %}
    <h2 class="form-signin-heading">用户登陆</h2>
    <input type="text" id="userName" name="username" class="form-control" placeholder="请输入用户名" required autofocus autocomplete="off" maxlength="10">
    <input type="password" id="userPwd" name="password" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">
    <a href="main.html"><button class="btn btn-lg btn-primary btn-block" type="submit" id="signinSubmit">登录</button></a>
  </form>
  <div class="footer">
    <p><a href="/backweb/register/" data-toggle="tooltip" data-placement="left" title="不知道自己在哪?">注册账号 →</a></p>
  </div>
</div>

</body>
</html>

templates/backweb/register.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>异清轩博客管理系统</title>
<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/css/login.css">
<link rel="apple-touch-icon-precomposed" href="/static/images/icon/icon.png">
<link rel="shortcut icon" href="/static/images/icon/favicon.ico">
<script src="/static/js/jquery-2.1.4.min.js"></script>
<!--[if gte IE 9]>
  <script src="/static/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="/static/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="/static/js/respond.min.js" type="text/javascript"></script>
  <script src="/static/js/selectivizr-min.js" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
  <script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
</head>

<body class="user-select">
{{ err_data }}
<div class="container">
  <div class="siteIcon"><img src="/static/images/icon/1.jpg" alt="" data-toggle="tooltip" data-placement="top" title="欢迎使用异清轩博客管理系统" draggable="false" /></div>
  <form action="" method="post" autocomplete="off" class="form-signin">
    {{ err_name }}
    {% csrf_token %}
    <h2 class="form-signin-heading">用户登陆</h2>
    <input type="text" id="userName" name="username" class="form-control" placeholder="请输入用户名" required autofocus autocomplete="off" maxlength="10">
    <input type="password" id="userPwd" name="password" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">
    <input type="password" id="userPwd2" name="password2" class="form-control" placeholder="请再次输入密码" required autocomplete="off" maxlength="18">
    <a href="main.html"><button class="btn btn-lg btn-primary btn-block" type="submit" id="signinSubmit">注册</button></a>
  </form>

</div>

</body>
</html>